# Generated by Django 3.1.6 on 2021-02-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0004_auto_20210209_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecart',
            name='category_id',
        ),
        migrations.AddField(
            model_name='ecart',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='categorymap',
        ),
    ]
